spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: ALWAYS

  profiles:
    active: local
    include: secret

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      maximum-pool-size: 20


kakao:
  rest:
    api:
      key: '${rest.api.key.kakao}'

open:
  api:
    key: '${rest.api.key.open}'

server:
  port: 8084