spring:
  datasource:
    url: '${local.url}'
    driver-class-name: org.mariadb.jdbc.Driver
    username: '${local.username}'
    password: '${local.password}'

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true