spring:
  datasource:
    url: '${dev.url}'
    driver-class-name: org.mariadb.jdbc.Driver
    username: '${dev.username}'
    password: '${dev.password}'

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true